apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aware-caribou-python
  janus-idp.io/tekton: aware-caribou-python
  backstage.io/kubernetes-id: aware-caribou-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aware-caribou-python
resources: 
- deployment.yaml
- route.yaml
- service.yaml
