apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aware-caribou-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aware-caribou-python 
  name: aware-caribou-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: aware-caribou-python 
